### ISSUE TITLE
Can we add a magnet texture?

### ISSUE THREAD

**Issue by yannickPineault** [racacax/openplanet_better_texture_mod#17]
Speedsplides on magnet are extremely effective (way more than on road), but custom skid marks on magnet don't work, so we can basically never see our skids on magnet. It's also just hard to know when it's magnet vs black platform. 

Tbh I'm not even sure if there are any skids on magnet though.

Is there any way to add a custom texture magnet that is not black, so that the basic black skids could be seen?

For now magnet is already in the plugin, but there's only one option for the texture, which is the default one, so we can't change it.

**Comment by racacax** [comment]
Hi,
In Trackmania, when there isn't a texture for a surface, it'll appear black. Magnet is black because... it doesn't have a texture :( Which means I cannot change a specific file like other surfaces to change the color. The only solution to this would to create new magnet block sets where we set an existing texture to the magnet material (we can technically make road blocks with grass textures in blender), but it'll be a very hard task to push this change.
I may be wrong about the absence of texture file and I'll ask on OpenPlanet Discord. But from my understanding, it's not possible :(

**Comment by racacax** [comment]
Well, seems like I have an answer. No magnet texture unless you apply the physics to existing material
![image](https://github.com/user-attachments/assets/cba005d6-ef0c-4261-89b8-97e7342dd423)

**Comment by yannickPineault** [comment]
Understood, thanks for the feedback!
